<x-submission-layout :forms="$forms">
  @slot('step1')
    @include('pages.manuscripts.form.upload-file')
  @endslot
  @slot('step2')
    Step2
  @endslot
  @slot('step3')
    step3
  @endslot
  @slot('step4')
    @include('pages.manuscripts.form.authors&institutions')
  @endslot
  @slot('step5')
    @include('pages.manuscripts.form.detail&form')
  @endslot
  @slot('step6')
  @endslot
</x-submission-layout>
